# .github/workflows/ci.yml

name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, close]
jobs:
  container-run:
    runs-on: ubuntu-latest
    container: xamarsia/ci-cd-playground:0.0.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Fix
        run: git config --global --add safe.directory '*'
      - uses: pre-commit/action@v3.0.1

#----------------------------------------------------

      # - name: Activate the CD virtual environment
      #   run: . ./scripts/cd-envsetup.sh && pre-commit install && pre-commit run --all-files --hook-stage manual || cat /github/home/.cache/pre-commit/pre-commit.log
